# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "21:37"
      timezone: "Europe/Warsaw"
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "21:37"
      timezone: "Europe/Warsaw"
    groups:
      uv:
        patterns: ["*"]
  - package-ecosystem: "gradle"
    directory: "/mobile"
    schedule:
      interval: "weekly"
      time: "21:37"
      timezone: "Europe/Warsaw"
    groups:
      gradle:
        patterns: ["*"]
